services:
  cairo:
    build: ./cairo
    environment:
      - RUN_SCRIPT=${RUN_SCRIPT:-test}
    env_file:
      - ./cairo/.env
    ports:
      - "8100:8100"
    volumes:
      # Code directories
      - ./cairo/src:/code/src
      - ./cairo/libs:/code/libs
      # Builds
      - ./cairo/build:/code/build
      # Logs and config
      - ./cairo/logs:/code/logs
      - ./shared/.starknet_accounts:/root/.starknet_accounts
      # Scripts
      - ./cairo/scripts.sh:/code/scripts.sh
      - ./cairo/run.sh:/code/run.sh
    command: sh -c "chmod -R +x ./scripts.sh ./run.sh && ./run.sh"
volumes:
  logvolume01: {}
